export const GET_POST_BY_ID = 'Detail/GET_POST_BY_ID';
export const SET_POST_BY_ID = 'Detail/SET_POST_BY_ID';
export const ADDCOMMENT_REQUEST = 'ADD/ADDCOMMENT_REQUEST';
export const EDITCOMMENT_REQUEST = 'EDIT/EDITCOMMENT_REQUEST';
export const DELETE_COMMENT_REQUEST = 'DELETE/DELETE_COMMENT_REQUEST';
export const FETCH_COMMENT_REQUEST = 'FETCH_COMMENT_REQUEST';
export const FETCH_COMMENT_SUCCESS = 'FETCH_COMMENT_SUCCESS';